version: '3.8'

services:

  # based on https://geshan.com.np/blog/2022/01/redis-docker/
  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379' # todo: don't expose the port on production
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local

